// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9UqTV0JUXv0FehVWusvxS3yJED4NwFpY',
    appId: '1:559371324681:web:af845036a50e29f0dc97d8',
    messagingSenderId: '559371324681',
    projectId: 'loginbackend-53afa',
    authDomain: 'loginbackend-53afa.firebaseapp.com',
    storageBucket: 'loginbackend-53afa.firebasestorage.app',
    measurementId: 'G-BRCY57RDP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ34BOua8pW6KkAmWsB8uPfcwlpYIq9wI',
    appId: '1:559371324681:android:cf685dd0712016badc97d8',
    messagingSenderId: '559371324681',
    projectId: 'loginbackend-53afa',
    storageBucket: 'loginbackend-53afa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTvVR5G7Ond3QQz875AA-ytUWsHoFrNPQ',
    appId: '1:559371324681:ios:c69fb7712d058e89dc97d8',
    messagingSenderId: '559371324681',
    projectId: 'loginbackend-53afa',
    storageBucket: 'loginbackend-53afa.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTvVR5G7Ond3QQz875AA-ytUWsHoFrNPQ',
    appId: '1:559371324681:ios:c69fb7712d058e89dc97d8',
    messagingSenderId: '559371324681',
    projectId: 'loginbackend-53afa',
    storageBucket: 'loginbackend-53afa.firebasestorage.app',
    iosBundleId: 'com.example.registration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9UqTV0JUXv0FehVWusvxS3yJED4NwFpY',
    appId: '1:559371324681:web:e6c0dddc5a4764bedc97d8',
    messagingSenderId: '559371324681',
    projectId: 'loginbackend-53afa',
    authDomain: 'loginbackend-53afa.firebaseapp.com',
    storageBucket: 'loginbackend-53afa.firebasestorage.app',
    measurementId: 'G-8ZSWMM6KRV',
  );
}
